### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by wooparadog** [Trinkler/katal-chain#55]
Hi, 

we've talked about in riot. I thought there might be some problems with my toolchain, so I did some digging. It appears that you shouldn't include sr-primitives in wasm. See diff bellow:

https://gist.githubusercontent.com/wooparadog/5936031c172ee3396772008acf54eec9/raw/d6ea518a07f1bb68d2d2e040300d7b2fe5bf27f5/gistfile1.txt

hope it helps

**Comment by brunoffranca** [comment]
Hi, thanks for opening the issue. It's very nice of you.
Unfortunately, your idea doesn't help. It isn't the master branch that doesn't build, it's the oracle-v2 branch. The sr-primitives module is not imported in any module. 
This is a very weird bug, I have no idea what's causing it.

**Comment by brunoffranca** [comment]
Hi, thanks for opening the issue. It's very nice of you.
Unfortunately, your idea doesn't help. It isn't the master branch that doesn't build, it's the oracle-v2 branch. The sr-primitives module is not imported in any module.
This is a very weird bug, I have no idea what's causing it.

**Comment by brunoffranca** [comment]
Found it! When importing a debug dependency I wrote "[dependencies.runtime_primitives]" instead of "[dev-dependencies.runtime_primitives]". Since the debug dependencies don't use the flag "default-features = false" the compiler was complaining of course.
